#!/usr/bin/env python3
"""Generates docs/protocol-support.md from the capability test's results.

The support table is derived from a real test run, never hand-written. The
previous hand-maintained table had drifted badly -- function keys, modifier
sequences, SO/SI and DECKPAM were all marked supported while the code did not
implement them -- and any table maintained by hand will drift again.

    tests/generate_protocol_support.py <path-to-qterm_capability_tests>

Status comes from what the test run reported, not from anyone's opinion:

    pass   -> supported      the assertion held on this build
    xfail  -> not supported  a known gap, with the reason the test recorded
    xpass  -> stale entry    implemented since; the test forces this to surface
    fail   -> broken         claimed but not working

Anything with no test at all is absent from the table, which is a third state:
"not assessed", distinct from "not supported".
"""

import subprocess
import sys
import xml.etree.ElementTree as ET
from collections import OrderedDict
from pathlib import Path

SYMBOL = {
    "pass": ("✅", "Supported"),
    "xfail": ("❌", "Not supported"),
    "xpass": ("⚠️", "Implemented — table entry is stale"),
    "fail": ("🔴", "Broken"),
}


def run_tests(binary: Path) -> str:
    result = subprocess.run(
        [str(binary), "-o", "-,xml"],
        capture_output=True,
        text=True,
        check=False,
    )
    return result.stdout


def parse(xml_text: str):
    root = ET.fromstring(xml_text)
    capabilities = []

    for function in root.iter("TestFunction"):
        declaration = None
        for message in function.iter("Message"):
            description = message.findtext("Description") or ""
            if description.startswith("CAPABILITY\t"):
                declaration = description.split("\t")[1:]
                break
        if not declaration or len(declaration) < 4:
            continue

        # An expected failure emits its own incident and then a passing one, so
        # the most severe incident is the one that describes the capability.
        severity = {"pass": 0, "xpass": 1, "xfail": 2, "fail": 3}
        status, reason = "pass", ""
        for incident in function.iter("Incident"):
            kind = incident.get("type", "pass")
            if severity.get(kind, 0) > severity.get(status, 0):
                status = kind
                reason = incident.findtext("Description") or ""

        identifier, group, description, reference = declaration[:4]
        capabilities.append(
            {
                "id": identifier,
                "group": group,
                "description": description,
                "reference": reference,
                "status": status,
                "reason": reason.strip(),
            }
        )
    return capabilities


def render(capabilities) -> str:
    grouped = OrderedDict()
    for capability in capabilities:
        grouped.setdefault(capability["group"], []).append(capability)

    supported = sum(1 for c in capabilities if c["status"] == "pass")
    total = len(capabilities)

    lines = [
        "# Protocol support",
        "",
        "<!-- Generated by tests/generate_protocol_support.py. Do not edit by hand. -->",
        "",
        "Generated from the results of `qterm_capability_tests`. Every entry below",
        "reflects an assertion that ran against this build, so the table cannot claim",
        "support the code does not have.",
        "",
        f"**{supported} of {total} assessed capabilities supported.**",
        "",
        "A capability that is absent from this table has not been assessed — which is",
        "not the same as unsupported. The enumeration covers what the target",
        "applications exercise; it is not the whole of ECMA-48.",
        "",
        "| | Meaning |",
        "|---|---|",
    ]
    for _, (symbol, meaning) in SYMBOL.items():
        lines.append(f"| {symbol} | {meaning} |")
    lines.append("")

    for group, entries in grouped.items():
        lines.append(f"## {group}")
        lines.append("")
        lines.append("| | Capability | Sequence | Notes |")
        lines.append("|---|---|---|---|")
        for capability in sorted(entries, key=lambda c: c["id"]):
            symbol = SYMBOL[capability["status"]][0]
            note = capability["reason"] if capability["status"] != "pass" else ""
            lines.append(
                f"| {symbol} | {capability['description']} "
                f"| `{capability['reference']}` | {note} |"
            )
        lines.append("")

    return "\n".join(lines)


def main() -> int:
    if len(sys.argv) < 2:
        print(__doc__)
        return 2

    binary = Path(sys.argv[1])
    if not binary.exists():
        print(f"no such test binary: {binary}", file=sys.stderr)
        return 1

    capabilities = parse(run_tests(binary))
    if not capabilities:
        print("no capabilities found -- did the test emit CAPABILITY lines?",
              file=sys.stderr)
        return 1

    output = Path(__file__).resolve().parent.parent / "docs" / "protocol-support.md"
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(render(capabilities) + "\n")
    print(f"wrote {output} ({len(capabilities)} capabilities)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
