#ifndef QTERMVTERMPROCESSOR_H
#define QTERMVTERMPROCESSOR_H

#include <QObject>
#include <QByteArray>
#include <QList>
#include <QVector>

#include <vterm.h>

/**
 * @brief Wraps libvterm, bridges PTY byte stream ↔ terminal screen model.
 *
 * Data flow:
 *  - PTY output  →  feedData()  → vterm_input_write() → screen callbacks
 *  - Keyboard    →  sendKey() / sendChar()  → libvterm → outputData signal → PTY
 *  - Mouse       →  sendMouseMove() / sendMouseButton() → libvterm → outputData → PTY
 *
 * The screen layer (VTermScreen) is used so that libvterm maintains the cell
 * buffer and scrollback history internally; we only react to damage callbacks
 * and query cells on demand.
 */
class QTermVTermProcessor : public QObject
{
    Q_OBJECT

public:
    explicit QTermVTermProcessor(int rows, int cols, QObject *parent = nullptr);
    ~QTermVTermProcessor() override;

    // --- Input from PTY ---
    void feedData(const QByteArray &data);

    // --- Resize ---
    void resize(int rows, int cols);

    // --- Keyboard → PTY ---
    void sendKey(VTermKey key, VTermModifier mod);
    void sendChar(uint32_t unichar, VTermModifier mod);
    void startPaste();
    void endPaste();

    // --- Mouse → PTY ---
    void sendMouseMove(int row, int col, VTermModifier mod);
    void sendMouseButton(int button, bool pressed, VTermModifier mod);

    // --- Screen queries ---
    int rows() const { return m_rows; }
    int cols() const { return m_cols; }
    VTermPos cursorPos() const { return m_cursorPos; }
    bool isCursorVisible() const { return m_cursorVisible; }

    /**
     * @brief Fetch a cell from the current visible screen.
     * @return true on success.
     */
    bool screenCellAt(int row, int col, VTermScreenCell *cell) const;

    // --- Scrollback ---
    int scrollbackLineCount() const { return m_scrollback.size(); }
    /**
     * @brief Return a scrollback line. Index 0 = most recently pushed line
     *        (just above the visible screen).
     */
    const QVector<VTermScreenCell> &scrollbackLine(int idx) const;

Q_SIGNALS:
    /** Rows [startRow, endRow) in the visible screen have changed. */
    void screenUpdated(int startRow, int endRow);

    /** Cursor position or visibility changed. */
    void cursorMoved(VTermPos pos, bool visible);

    /** Terminal title changed (OSC 0/2). */
    void titleChanged(const QString &title);

    /** Terminal bell. */
    void bellRang();

    /**
     * @brief Raw bytes that must be forwarded to the PTY.
     * Generated by libvterm in response to keyboard/mouse events and
     * terminal query responses (DA, DSR, etc.).
     */
    void outputData(const QByteArray &data);

    /** libvterm requested a resize (rare). */
    void resized(int rows, int cols);

public:
    // --- libvterm screen callbacks (must be public for the static callback table) ---
    static int cb_damage(VTermRect rect, void *user);
    static int cb_moverect(VTermRect dest, VTermRect src, void *user);
    static int cb_movecursor(VTermPos pos, VTermPos oldpos, int visible, void *user);
    static int cb_settermprop(VTermProp prop, VTermValue *val, void *user);
    static int cb_bell(void *user);
    static int cb_resize(int rows, int cols, void *user);
    static int cb_sb_pushline(int cols, const VTermScreenCell *cells, void *user);
    static int cb_sb_popline(int cols, VTermScreenCell *cells, void *user);
    static int cb_sb_clear(void *user);

    // --- libvterm output callback ---
    static void cb_output(const char *s, size_t len, void *user);

    /** Emit accumulated damage and reset tracking. */
    void flushDamage();

    // --- libvterm handles ---
    VTerm       *m_vt     = nullptr;
    VTermScreen *m_screen = nullptr;

    int m_rows;
    int m_cols;

    VTermPos m_cursorPos{0, 0};
    bool     m_cursorVisible = true;

    // Accumulated damage (row range within the visible screen)
    int m_damageStartRow = -1;
    int m_damageEndRow   = -1;

    // Scrollback buffer; index 0 = topmost line (last pushed)
    static constexpr int kMaxScrollbackLines = 5000;
    QList<QVector<VTermScreenCell>> m_scrollback;
};

#endif // QTERMVTERMPROCESSOR_H
